### PR TITLE
fix: Improve input validation on query execution

### PR DESCRIPTION
**Pull request by josh18**
- Removes scalar validation as it is impossible to know what data type it should validate.
- Fixes JSON objects passing Int / Float / Boolean validation

@acao

### CODE REVIEW

**Comment by acao** [comment]
thanks @josh18, was meaning to get to this!

can you add `ID` to the known scalar types and validate for string?

**Comment by acao** [comment]
ah, i can just add that myself later. thanks!

**Comment by josh18** [comment]
:+1: thanks!

> can you add ID to the known scalar types and validate for string?

Not sure how you are going to validate that, isn't the user input always a string?

**Comment by acao** [comment]
yes so you would then add a case statement for `ID`, that validates for `string`, though as you can see in the spec I linked to, it is expected to coerce from number or string. guess it’s not a big deal, but a user did request it already in another ticket

**Pull request merged**
