### PR TITLE
improvement: associate with graphqls file extension

### LINKED ISSUE #176: Extension not associated with `.graphqls` files
## Actual Behavior
While this extension supports `.graphqls` files, Visual Studio Code is not aware of it.

## Expected Behavior
Associate this extension with `.graphqls` files.

## Steps to Reproduce the Problem Or Description
Open a `.grapphqls` file:
- without this extension installed, it is not recommended at all by Visual Studio Code
- with this extension installed, the file is not associated nor handled by the extension

## Specifications

  - GraphQL for VSCode Extension Version: 0.2.14
  - VSCode Version: 1.44.2
  - OS Name: Debian GNU/Linux
  - OS Version: bullseye/testing

## Logs Of TS Server || GraphQL Language Service
Not relevant

### PR DESCRIPTION
**Pull request by cailloumajor**
Fixes #176

### CODE REVIEW

**Comment by acao** [comment]
and here as well

https://github.com/prisma-labs/vscode-graphql/blob/6f1e9252f9b5074333b02999d12cfc54f46a0859/src/extension.ts#L76

**Comment by cailloumajor** [comment]
PR updated, thank you for the indications.

**Comment by acao** [comment]
I'll be cutting a new pre-release of the language server by monday, so once we cut that, we can bump the dependency in this PR and be good to go!

**Comment by acao** [comment]
@cailloumajor ok! the stable release of `graphql-language-service-server` is out, and we just merged a package bump, so this PR is good to go!

**Pull request merged**
