### PR TITLE
feat: upgrade graphql-config, language server

### LINKED ISSUE #124: Use environment variables
Thank you for this plugin.

Is there a way to set then access env variables? Let's say I need to connect to github API, I don't want to write my github token in `.graphqlconfig.yml`. Is there a way to set then use env vars?

### PR DESCRIPTION
**Pull request by acao**
## TODO 
- [x] upgrade `graphql-config` and `graphql-language-service-server`
- [x] load graphql config/schema using @3 API
- [x] update readme
- [x] enable jsx/tsx/ts language features (before only highlighting was enabled, except for `.js`)
- [x] headers and env
- [x] get operations working with new endpoints extension (default to `schema` url if provided)
- [x] improve error handling for requests
- [x] variables validation for requests
- [x] remove requirement for typescript LSP extension

resolves #124 #145 #171 #165 #116 #184 
requires:
https://github.com/graphql/graphiql/pull/1616

*UPDATE*: you can provide feedback for the `graphql.graphql-vscode-insiders` extension 0.3.5 to test this PR and it's dependent releases in #184

### CODE REVIEW

**Comment by acao** [comment]
oops this was supposed to be a draft haha

**Comment by matt-huh** [comment]
Any update to this PR? I'm waiting for days...

**Comment by acao** [comment]
@matt-huh  whole days, huh? welcome to OSS! :laughing: 

still working on several required PRs to the LSP server that this depends on. will need to publish about 24 new NPM package versions before I can even finish this PR.  this branch is what I used for reference while developing the LSP changes.

**Comment by matt-huh** [comment]
@acao Thanks for sharing the status. I'm always grateful for all the great contributions made - no intention to push!

**Comment by acao** [comment]
good news folks! this is very close. close enough to test very easily

prisma folks and I are still working out a few details, and deciding whether/how to pre-release this, or whether to just issue a full stable release. I still need to finish updating the prisma graphql config extension that this depends on.

testing instructions:
1. clone this repo, check out this branch `chore/graphql-config-3`
1. npm install
1. open in vscode
1. open debugger tab, run `"Run (Extension)"`
1. open a project with a `graphql-config@3` config (`schemaPath` -> `schema`, `includes` -> `documents`, use `.js` and `process.env` instead of funky old  yaml env template replacement, etc

I think the documentation could use more information, and that it would be nice to start a changelog with this PR

**Comment by acao** [comment]
good news!

you can install from the marketplace now:

https://github.com/prisma-labs/vscode-graphql/issues/181#issuecomment-672337523

**Comment by huv1k** [comment]
I am getting a lot of errors, what is the best way to provide feedback? Like this for example:

**Comment by acao** [comment]
@huv1k let's provide feedback here #181. try 0.3.5 update and a reload!

**Pull request merged**
